# Generated by Django 5.1.1 on 2024-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
